#!/bin/sh
#load and unload modules hello, scull and faulty

case "$1" in
    start)
    #Since the modules where all loaded in the Kernel I just have to call them to load
        echo "Loading aesdchar-driver driver..."
        cd /lib/modules/6.1.44/extra && ls
        aesdchar_load

        ;;
    stop)
    #Since the modules where all loaded in the Kernel I just have to call them to unload
        echo "Unloading aesdchar-driver driver..."
        cd /lib/modules/6.1.44/extra
        aesdchar_unload

        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1;
        ;;
esac

exit 0